if (GetLocale() == "deDE") then
	-- Buttons and Titles
	PERL_LOCALIZED_CONFIG_ALL = "Alle";
	PERL_LOCALIZED_CONFIG_ARCANEBAR = "ArcaneBar";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY = "CombatDisplay";
	PERL_LOCALIZED_CONFIG_FOCUS = "Fokus";
	PERL_LOCALIZED_CONFIG_FOCUSTARGET = "Fokus Ziel";
	PERL_LOCALIZED_CONFIG_FOCUSPARTYTARGET = "Fokus/Gruppe Ziel";
	PERL_LOCALIZED_CONFIG_PARTY = "Gruppe";
	PERL_LOCALIZED_CONFIG_PARTYPET = "Gruppen Begleiter";
	PERL_LOCALIZED_CONFIG_PARTYTARGET = "Gruppen Ziel";
	PERL_LOCALIZED_CONFIG_PLAYER = "Spieler";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF = "Spieler-Buffs";
	PERL_LOCALIZED_CONFIG_PLAYERPET = "Spieler Begleiter";
	PERL_LOCALIZED_CONFIG_TARGET = "Ziel";
	PERL_LOCALIZED_CONFIG_TARGETTARGET = "Ziel des Ziel";

	-- Perl Config Shared Strings
	PERL_LOCALIZED_CONFIG_TRANSPARENCY = "Transparenz";
	PERL_LOCALIZED_CONFIG_SCALING = "Skalierung";
	PERL_LOCALIZED_CONFIG_SCALING_SET_CURRENT = "Aktuelle UI-Skalierung \195\188bernehmen";
	PERL_LOCALIZED_CONFIG_MISC = "Sonstiges";
	PERL_LOCALIZED_CONFIG_DISPLAY_MODE = "Anzeigemodus";
	PERL_LOCALIZED_CONFIG_DRUIDBAR = "DruidBar Unterst\195\188tzung";
	PERL_LOCALIZED_CONFIG_RESET_FRAMES = "Positionen zur\195\188cksetzen";
	PERL_LOCALIZED_CONFIG_PORTRAITS = "Portrait anzeigen";
	PERL_LOCALIZED_CONFIG_THREED_PORTRAITS = "3D Portrait";
	PERL_LOCALIZED_CONFIG_ALWAYS_SHOWN = "Immer anzeigen";
	PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID = "In Schlachtz\195\188gen verstecken";
	PERL_LOCALIZED_CONFIG_ALWAYS_HIDDEN = "Immer verstecken";
	PERL_LOCALIZED_CONFIG_BUFF_LOCATION = "Buff Position";
	PERL_LOCALIZED_CONFIG_DEBUFF_LOCATION = "Debuff Position";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_SMALL = "Buff Gr\195\182\195\159e (Standardm\195\164\195\159ig 12)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_SMALL = "Debuff Gr\195\182\195\159e (Standardm\195\164\195\159ig 12)";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_LARGE = "Buff Gr\195\182\195\159e (Standardm\195\164\195\159ig 16)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_LARGE = "Debuff Gr\195\182\195\159e (Standardm\195\164\195\159ig 16)";
	PERL_LOCALIZED_CONFIG_BUFF_NUMBER = "# Buffs";
	PERL_LOCALIZED_CONFIG_DEBUFF_NUMBER = "# Debuffs";
	PERL_LOCALIZED_CONFIG_COMBAT_TEXT = "Kampftext";
	PERL_LOCALIZED_CONFIG_COMPACT = "Kompakter Modus";
	PERL_LOCALIZED_CONFIG_DISPLAY_PERCENTS = "Prozente anzeigen";
	PERL_LOCALIZED_CONFIG_SHORT_BARS = "Kurze Leisten";
	PERL_LOCALIZED_CONFIG_VERTICAL_FRAMES = "Vertikale Fenster";
	PERL_LOCALIZED_CONFIG_HIDE_CLASSICON_FRAME = "Klassensymbol Fenster verstecken";
	PERL_LOCALIZED_CONFIG_HEALER_MODE = "Heiler-Modus";
	PERL_LOCALIZED_CONFIG_PET_SUPPORT = "Begleiterleisten anzeigen";
	PERL_LOCALIZED_CONFIG_CLASS_COLORED_NAMES = "Farbige Klassennamen";
	PERL_LOCALIZED_CONFIG_SMALL = "Klein";
	PERL_LOCALIZED_CONFIG_BIG = "Gro\195\159";
	PERL_LOCALIZED_CONFIG_HIDE_POWER_BARS = "Verstecke Power Leisten";
	PERL_LOCALIZED_CONFIG_DISPLAY_MANA_DEFICIT = "Mana-Defizit anzeigen"
	PERL_LOCALIZED_CONFIG_PVP_STATUS_ICON = "PvP Symbol";
	PERL_LOCALIZED_CONFIG_SHOW_BAR_VALUES = "Leistenwerte anzeigen";
	PERL_LOCALIZED_CONFIG_INVERT_BAR_VALUES = "Leistenwerte umkehren";
	PERL_LOCALIZED_CONFIG_COLOR_FRAME_DEBUFF = "Fenster nach Debuff f\195\164rben";
	PERL_LOCALIZED_CONFIG_CLASS_BUFF = "Nur Klassenbuffs";
	PERL_LOCALIZED_CONFIG_CLASS_DEBUFF = "Nur heilbare Debuffs";
	PERL_LOCALIZED_CONFIG_ALIGN_HORIZONTALLY = "Horizontal ausrichten";
	PERL_LOCALIZED_CONFIG_THREAT_ICONS = "Bedrohungssymbole";
	PERL_LOCALIZED_CONFIG_MY_DEBUFFS = "Nur meine Debuffs"

	-- Perl Config Generic
	PERL_LOCALIZED_CONFIG_HEADER = "Perl Einstellungen";
	PERL_LOCALIZED_CONFIG_CLOSE = "Schlie\195\159en";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED = "Nicht installiert";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED_EXPLANATION = "Dieses AddOn ist nicht installiert oder aktiviert.";

	-- Perl Config All
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BARS = "Leistentextur";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_ONE = "Textur #1";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_TWO = "Textur #2";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_THREE = "Textur #3";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FOUR = "Textur #4";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FIVE = "Textur #5";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_SIX = "Textur #6";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_NONE = "Keine Textur";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_POSITION = "Position des Minimap Symbols ";
	PERL_LOCALIZED_CONFIG_ALL_SHOW_MINIMAP = "Minimap Symbol anzeigen";
	PERL_LOCALIZED_CONFIG_ALL_FRAMES = "Fenster";
	PERL_LOCALIZED_CONFIG_ALL_TRANSPARENT_BACKGROUND = "Transparenter Hintergrund";
	PERL_LOCALIZED_CONFIG_ALL_LOCK_ALL = "Alle Fenster fixieren";
	PERL_LOCALIZED_CONFIG_ALL_UNLOCK_ALL = "Alle Fenster freigeben";
	PERL_LOCALIZED_CONFIG_ALL_LOAD = "Einstellungen laden";
	PERL_LOCALIZED_CONFIG_ALL_SAVE = "Einstellungen speichern";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Einstellungen geladen.";
	PERL_LOCALIZED_CONFIG_ALL_SAVE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Einstellungen gespeichert.";
	PERL_LOCALIZED_CONFIG_ALL_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Fensterpositionen wurde zur\195\188ckgesetzt.";
	PERL_LOCALIZED_CONFIG_ALL_CLICKHEALING = "CastParty/Genesis/AceHeal/ClickHeal Unterst\195\188tzung";
	PERL_LOCALIZED_CONFIG_ALL_PROGRESSIVE = "Farbige Gesundheitsleisten";
	PERL_LOCALIZED_CONFIG_ALL_NO_PROFILE_SELECTED_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Es wurde kein Profil ausgew\195\164hlt.";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Profileinstellungen geladen: ";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_HEADER = "Profil ausw\195\164hlen:";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_BUTTON = "Laden";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_BUTTON = "L\195\182schen";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Das folgende Profil wurde aus der Liste gel\195\182scht: ";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BACKGROUND = "Textur f\195\188r Leistenhintergrund";
	PERL_LOCALIZED_CONFIG_ALL_FADE_BARS = "Leisten verblassen";
	PERL_LOCALIZED_CONFIG_ALL_CLICKCASTABLE_NAME_FRAMES = "Make Name Frames Click Castable";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_RADIUS = "Radius des Minimap Symbols";
	PERL_LOCALIZED_CONFIG_ALL_POSITIONING_MODE = "Positionierung-Modus";
	PERL_LOCALIZED_CONFIG_ALL_POSITIONING_MODE_TOOLTIP = "Diese Option ist ausschlie\195\159lich zum Positionieren der Fenster!\nText 'Fehler' sind normal und m\195\188ssen nicht gemeldet werden.\nDiese Option funktioniert am Besten, wenn Du kein Ziel hast und die Titel der Fenster sich somit nicht ver\195\164ndern.";

	-- Perl Config ArcaneBar
	PERL_LOCALIZED_CONFIG_ARCANEBAR_ENABLE = PERL_LOCALIZED_CONFIG_ARCANEBAR.." aktivieren";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_DISPLAY_TIMER = "Zeige Zauber-Timer";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_HIDE_BLIZZARD = "Verstecke Blizzard Zauberleiste";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_REPLACE_NAME = "Spielername mit Zaubername ersetzen";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_LEFT_TIMER = "Left Align Cast Timer";

	-- Perl Config CombatDisplay
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_PERSIST_MODES = "Persist Modes";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_TARGET_SETTINGS = "Ziel Einstellungen";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_AUTOATTACK = "w/ Auto Angriff";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ONAGRO = "Bei Aggro";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_HEALTH_PERSIST = "Health Persistance";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MANA_PERSIST = "Mana Persistance";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MENU = "Rechts-Klick f\195\188r das Men\195\188";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_LOCK = PERL_LOCALIZED_CONFIG_COMBATDISPLAY.." fixieren";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ENABLE_TARGET = "Ziel aktivieren";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_DISPLAY_COMBOPOINT_BAR = "Kombopunkten-Leiste anzeigen";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_CLICK_THROUGH = "Durch Fenster klicken";

	-- Perl Config Party
	PERL_LOCALIZED_CONFIG_PARTY_SPACING = "Abstand (Standardm\195\164\195\159ig 95)";
	PERL_LOCALIZED_CONFIG_PARTY_FKEYS = "F Tasten anzeigen";
	PERL_LOCALIZED_CONFIG_PARTY_LOCK = PERL_LOCALIZED_CONFIG_PARTY.." fixieren";
	PERL_LOCALIZED_CONFIG_PARTY_PORTRAITBUFFS = "Buffs an Portraits ausrichten";

	-- Perl Config Party Pet
	PERL_LOCALIZED_CONFIG_PARTYPET_ENABLE = PERL_LOCALIZED_CONFIG_PARTYPET.." aktivieren";
	PERL_LOCALIZED_CONFIG_PARTYPET_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": "..PERL_LOCALIZED_CONFIG_PARTYPET.." Frame Positionen wurden zur\195\188ckgesetzt.";
	PERL_LOCALIZED_CONFIG_PARTYPET_LOCK = PERL_LOCALIZED_CONFIG_PARTYPET.." fixieren";

	-- Perl Config Party Target
	PERL_LOCALIZED_CONFIG_PARTYTARGET_ENABLE = PERL_LOCALIZED_CONFIG_PARTYTARGET.." aktivieren";
	PERL_LOCALIZED_CONFIG_FOCUSTARGET_ENABLE = PERL_LOCALIZED_CONFIG_FOCUSTARGET.." aktivieren";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_LOCK = PERL_LOCALIZED_CONFIG_FOCUSPARTYTARGET.." fixieren";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_PARTY_HIDDEN_IN_RAID = PERL_LOCALIZED_CONFIG_PARTYTARGET.." "..PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID;
	PERL_LOCALIZED_CONFIG_PARTYTARGET_FOCUS_HIDDEN_IN_RAID = PERL_LOCALIZED_CONFIG_FOCUSTARGET.." "..PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID;
	PERL_LOCALIZED_CONFIG_PARTYTARGET_SCALE = PERL_LOCALIZED_CONFIG_PARTY.." "..PERL_LOCALIZED_CONFIG_TARGET.." "..PERL_LOCALIZED_CONFIG_SCALING;
	PERL_LOCALIZED_CONFIG_FOCUSTARGET_SCALE = PERL_LOCALIZED_CONFIG_FOCUS.." "..PERL_LOCALIZED_CONFIG_TARGET.." "..PERL_LOCALIZED_CONFIG_SCALING;

	-- Perl Config Player
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_MODE = "Erfahrungsleisten Modus";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_EXPERIENCE = "Erfahrung";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_PVPRANK = "PvP Rang";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_REPUTATION = "Ruf";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_HIDDEN = "Versteckt";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP = "Gruppennummer anzeigen";
	PERL_LOCALIZED_CONFIG_PLAYER_LOCK = PERL_LOCALIZED_CONFIG_PLAYER.." fixieren";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP_IN_NAME = "Gruppennummer beim Name anzeigen";
	PERL_LOCALIZED_CONFIG_PLAYER_FIVE_SECOND_RULE = "5-Sekunden-Regel";
	PERL_LOCALIZED_CONFIG_PLAYER_PVP_TIMER = "PvP-Timer";

	-- Perl Config Player Buff
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_ENABLE = "Spieler-Buffs aktivieren";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_WARNING = "30-Sekunden Zauberwarnungen aktivieren";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HIDESECONDS = "Sekunden verstecken";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HORIZONTAL_SPACING = "Horizontaler Abstand (Standardm\195\164\195\159ig 10)";

	-- Perl Config Player Pet
	PERL_LOCALIZED_CONFIG_PLAYERPET_EXPERIENCE = "Erfahrungsleiste aktivieren";
	PERL_LOCALIZED_CONFIG_PLAYERPET_LOCK = PERL_LOCALIZED_CONFIG_PLAYERPET.." fixieren";
	PERL_LOCALIZED_CONFIG_PLAYERPET_HIDENAME = "Name verstecken";
	PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET = "Begleiter Ziel";
	PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET_ENABLE = PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET.." aktivieren";
	PERL_LOCALIZED_CONFIG_PLAYERPET_SCALE = PERL_LOCALIZED_CONFIG_PLAYERPET.." "..PERL_LOCALIZED_CONFIG_SCALING;
	PERL_LOCALIZED_CONFIG_PLAYERPET_TARGET_SCALE = PERL_LOCALIZED_CONFIG_PLAYERPET.." "..PERL_LOCALIZED_CONFIG_TARGET.." "..PERL_LOCALIZED_CONFIG_SCALING;

	-- Perl Config Target
	PERL_LOCALIZED_CONFIG_TARGET_BUFFDEBUFF_SCALING = "Buff/Debuff Skalierung (Standardm\195\164\195\159ig 100)";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_LOCATION = "Kombo-Position";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_ICON = "Klassensymbol";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_FRAME = "Klassenfenster";
	PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME = "Rar/Elite Fenster";
	PERL_LOCALIZED_CONFIG_TARGET_HIDE_BUFFDEBUFF_BACKGROUND = "Buff/Debuff Hintergrund verstecken";
	PERL_LOCALIZED_CONFIG_TARGET_SOUND_ON_TARGET_CHANGE = "Sound bei Zielwechsel";
	PERL_LOCALIZED_CONFIG_TARGET_LOCK = PERL_LOCALIZED_CONFIG_TARGET.." fixieren";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_POINT_FRAME = "Kombopunkte";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_IN_NAME_FRAME = "Beim Namen anzeigen";
	PERL_LOCALIZED_CONFIG_TARGET_DEBUFF_STACKS_IN_COMBO_FRAME = "Debuff stapelt in Kombo-Fenster";
	PERL_LOCALIZED_CONFIG_TARGET_ALTERNATE_FRAME_STYLE = "Alternativer Fenster-Style";
	PERL_LOCALIZED_CONFIG_TARGET_INVERT_BUFFS_DEBUFFS = "Buffs/Debuffs umkehren";
	PERL_LOCALIZED_CONFIG_TARGET_GUILD_FRAME = "Gildenname";
	PERL_LOCALIZED_CONFIG_TARGET_ELITE_RARE_GRAPHIC = "Rar/Elite Grafik";
	PERL_LOCALIZED_CONFIG_TARGET_BUFF_DEBUFF_TIMERS = "Buff/Debuff Timer";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_NUMERIC_THREAT = "Bedrohung in Zahlen anzeigen";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_NUMERIC_THREAT_TOOLTIP = "Sollte diese Einstellung aktiviert sein, ist die '"..PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME.."' Einstellung nicht verf\195\188gbar.";

	-- Perl Config Target Target
	PERL_LOCALIZED_CONFIG_TARGETTARGET_MAIN = "Main";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_MODE = "Alarm-Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_SIZE = "Alarm Gr\195\182\195\159e";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOT = "Ziel des Ziels aktivieren";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOTOT = "Ziel des Ziel des Ziels aktivieren";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_AUDIO_ALERT_ON_AGRO = "Audio-Alarm bei Aggro";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LOCK = PERL_LOCALIZED_CONFIG_TARGETTARGET.." fixieren";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_BUFFS = "Zeige ZdZ Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_DEBUFFS = "Zeige ZdZ Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_BUFFS = "Zeige ZdZdZ Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_DEBUFFS = "Zeige ZdZdZ Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_DPS_MODE = "DPS-Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TANK_MODE = "Tank-Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_HEALER_MODE = "Heiler-Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SMALL_TEXT = "Kleiner Text";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LARGE_TEXT = "Gro\195\159er Text";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_NO_TEXT = "Kein Text";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OF_TARGET_FRAME = "Rechts vom Zielfenster";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OF_TARGET_FRAME = "\195\156ber dem Zielfenster";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Ziel des Ziels Fenster wurden 'Rechts ausgerichtet'.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Ziel des Ziels Fenster wurden 'Oben ausgerichtet'.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_FRIENDLY_HEALTH = "Gesundheitswerte anzeigen";
end
